### ISSUE TITLE
Tab close button

### ISSUE THREAD

**Issue by robeden** [yole/jitwatch-intellij#4]
It could really use a close button for the tab to get rid of the tab and related data in the editor (similar to closing the code coverage tab).

(Great plugin, thanks!)

**Comment by yole** [comment]
You can use Analyze | Close HotSpot Compilation Log for this.

**Comment by robeden** [comment]
Ok, thanks... though that wasn't very obvious so you might still want to think about a close button (more consistent with standard tools).
